### ISSUE TITLE
RelyingParty.TokenLifeTime documented as hours but used as minutes

### ISSUE THREAD

**Issue by gleizerowicz** [IdentityServer/Thinktecture.IdentityServer3.WsFederation#14]
Documentation says to set the RelyingPartyTokenLifeTime in hours but SignInResponse.CreateSecurityToken() uses the value as minutes:

Lifetime = new Lifetime(DateTime.UtcNow, DateTime.UtcNow.AddMinutes(validationResult.RelyingParty.TokenLifeTime))

**Comment by leastprivilege** [comment]
thanks!

**Comment by gleizerowicz** [comment]
My pleasure!  Wasn't sure how you wanted to handle it, using a TimeSpan would be nice but obviously is a breaking change...

**Comment by leastprivilege** [comment]
done
