### ISSUE TITLE
[Question] Which Stores/Repositories are significant for WsFederation?

### ISSUE THREAD

**Issue by rayph** [IdentityServer/Thinktecture.IdentityServer3.WsFederation#20]
If for example IdSrv3 using WsFed was deployed into a web farm environment, which repositories require or would be highly recommended for shared state/storage instead of just in-memory stores?  

(It seems there are quite a few OIDC specific stores for different things but I would like to focus specifically on WsFed)

**Comment by leastprivilege** [comment]
Actually none of them besides Users

**Comment by rayph** [comment]
Ok, I have a User + Roles store...

Somehow I expected something to do with tokens might be important in a web farm / multi server environment, is this not the case?

**Comment by leastprivilege** [comment]
WS-Fed is a simple request/response protocol and does not keep state (like e.g. the code flow in OIDC)

**Comment by rayph** [comment]
Great, the number of store/repo options in IdSrv made it feel ambiguous.. 
Thanks for the quick answers! :)
