### ISSUE TITLE
Usage of OwinEnvironmentService not supported

### ISSUE THREAD

**Issue by VictorBlomberg** [IdentityServer/Thinktecture.IdentityServer3.WsFederation#21]
Hi,

The WsFederation plugin seems to lack support for [OwinEnvironmentService](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Services/OwinEnvironmentService.cs). If I understand it correctly the [WsFederation AutofacConfig](https://github.com/IdentityServer/Thinktecture.IdentityServer3.WsFederation/blob/master/source/WsFederationPlugin/Configuration/Hosting/AutofacConfig.cs#L60) lacks the OwinEnvironmentService setup from  the [Core AutofacConfig:124](https://github.com/IdentityServer/Thinktecture.IdentityServer3/blob/master/source/Core/Configuration/Hosting/AutoFacConfig.cs#L124). But since the OwinEnvironmentService constructor is `internal`, it's not as simple as just adding support for it in the WsFederation plugin.

This is an issue if your UserService uses the OwinEnvironmentService, since the SignInResponseGenerator in the WsFederation plugin requires UserService, and thus won't be able to resolve the dependency, causing an exception to be thrown.

Victor

**Comment by brockallen** [comment]
Yep, we can add that.

**Comment by brockallen** [comment]
Added this to the dev branch. You should now be able accept the owin environment service (from core) as an injectable.
