### ISSUE TITLE
[Question] Is there a way to revoke previously issued tokens for an authenticated user?

### ISSUE THREAD

**Issue by rayph** [IdentityServer/Thinktecture.IdentityServer3.WsFederation#26]
I would like to force a user to sign-in again by revoking the issued tokens if for instance the user needed to be blocked/barred with immediate effect. 

Is there a way to do this?

**Comment by brockallen** [comment]
This is what IsActive is for on the user service.

https://identityserver.github.io/Documentation/docs/advanced/userService.html

This will only affect new tokens or use of reference tokens from an API that has not cached the reference token result.

**Comment by rayph** [comment]
This doesn't get called all of the time though or am I missing something?

**Comment by brockallen** [comment]
I clarified what I wrote above, because I missed a scenario.

In any event, for SAML tokens that have already been issued for login the IsActive won't (and can't) affect them.

**Comment by rayph** [comment]
Yes, that is what I am seeing... Is there a pattern for revoking the tokens?

**Comment by brockallen** [comment]
Each app would have to contact IdSvr (or the DB or wherever you keep your flag) each time the user access the app. Not sure you want to do that though..

**Comment by rayph** [comment]
I'm hoping for something a bit more generic since the other apps do not access the same data stores

**Comment by brockallen** [comment]
You'd have to build this feature yourself.

**Comment by rayph** [comment]
Is this also the case when wanting to force claims to be up-to-date?

**Comment by brockallen** [comment]
Yes, you have to go back to the STS if you want an updated token.
